include:
  - board: rp2354_split_left/rp2350b/m33/zmk
    artifact-name: rp2354_split_left_usb_app_focus_ladder
    cmake-args: -DEXTRA_DTC_OVERLAY_FILE=$PWD/config/left_usb_app_focus_ladder.overlay -DEXTRA_CONF_FILE=$PWD/config/left_usb_app_focus_ladder.conf

  - board: rp2354_split_left/rp2350b/m33/zmk
    artifact-name: rp2354_split_left
    snippet: rp2-boot-mode-retention

  - board: rp2354_split_right/rp2350b/m33/zmk
    artifact-name: rp2354_split_right
    snippet: rp2-boot-mode-retention
