CONFIG_ZMK_SPLIT=n
CONFIG_ZMK_SPLIT_WIRED=n
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=n
CONFIG_ZMK_USB=n
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n

CONFIG_F22_DEBUG_PROBE=y
CONFIG_F22_DEBUG_PROBE_USB_ARMED=y
